export const images = {
  logo: require('../../assets/images/logo.png'),
  confirmEmail: require('../../assets/images/confirmEmail.png'),
  alertModalSuccess: require('../../assets/images/alertModalSuccess.png'),
  alertModalWarning: require('../../assets/images/alertModalWarning.png'),
  alertModalError: require('../../assets/images/alertModalError.png'),
  noConnection: require('../../assets/images/noConnection.png'),
  noImages: require('../../assets/images/noImages.png'),
  genderX: require('../../assets/images/genderX.png'),
  genderY: require('../../assets/images/genderY.png'),
  comingSoon: require('../../assets/images/comingSoon.png'),
  angry: require('../../assets/images/angry.png'),
  sad: require('../../assets/images/sad.png'),
  happy: require('../../assets/images/happy.png'),
  loving: require('../../assets/images/loving.png'),
  calm: require('../../assets/images/calm.png'),
  sick: require('../../assets/images/sick.png'),
  stress: require('../../assets/images/stress.png'),
};
